# Makefile for building and generating MLS SDK bindings

# Build for Android
build-android:
	../../scripts/mls_uniffi_build_android.sh

# Build for iOS
build-ios:
	../../scripts/mls_uniffi_build_ios.sh
